import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {spawnSync} from 'node:child_process';
import {mkdtempSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {voyageSettings} from '../resources/js/voyage-settings.js';

const until = async (predicate, describe=()=> 'settings did not settle') => { for (let i=0;i<100;i++) { if(predicate()) return; await new Promise(r=>setTimeout(r,5)); } assert.fail(describe()); };
test('owner connection can choose a new folder; scoped connections retain their workspace list', async (t) => {
    const compiled=mkdtempSync(join(tmpdir(),'helm-owner-views-'));
    t.after(()=>rmSync(compiled,{recursive:true,force:true}));
    const rendered = spawnSync('php',['-r',`require 'vendor/autoload.php'; $app=require 'bootstrap/app.php'; $app->make(Illuminate\\Contracts\\Console\\Kernel::class)->bootstrap(); view()->share('errors',new Illuminate\\Support\\ViewErrorBag()); echo view('livewire.console',['vessels'=>collect(),'tenantId'=>'owner-test'])->render();`],{cwd:new URL('..',import.meta.url),encoding:'utf8',env:{...process.env,VIEW_COMPILED_PATH:compiled}});
    assert.equal(rendered.status,0,rendered.stderr);
    const dom = new JSDOM(rendered.stdout,{url:'https://console.example'});
    for (const key of ['window','document','localStorage','Event']) globalThis[key]=dom.window[key];
    const root=document.querySelector('#helm-client'), field=id=>root.querySelector(`#${id}`);
    const profileOption=()=>root.querySelector('#edit-profile ui-option[data-settings-option]');
    let scope='owner'; const seen=[]; let selected, origin, unavailableText;
    const account={account_id:'10000000-0000-4000-8000-000000000001',connection_id:'10000000-0000-4000-8000-000000000002',identity_generation:1,connection_revision:1,transport:'openai_responses'};
    let profiles={revision:1,can_manage:true,default_profile_id:'default',profiles:[{id:'default',name:'Default',account,model:'model',reasoning_effort:null,service_tier:null}]};
    const client={exchange:async envelope=>{
        const c=envelope.command; seen.push(c);
        let result;
        if(c.op==='capabilities') result={vessel_id:'vessel',scope,rights:scope==='owner'?[]:['create','account_use'],workspaces:[{name:'Known',path:'/known'}]};
        else if(c.op==='accounts') result={accounts:[{id:account.account_id,connection_id:account.connection_id,identity_generation:1,state:'ready',availability:'available',label:'Account'}],connections:[{id:account.connection_id,revision:1,transports:[account.transport],label:'Provider'}]};
        else if(c.op==='profiles') result=structuredClone({...profiles,can_manage:scope==='owner'});
        else if(c.op==='save_profile') {assert.equal(c.expected_revision,profiles.revision);profiles.profiles.push(c.profile);profiles.revision++;result=structuredClone(profiles);}
        else if(c.op==='set_default_profile') {profiles.default_profile_id=c.profile_id;profiles.revision++;result=structuredClone(profiles);}
        else if(c.op==='delete_profile') {profiles.profiles=profiles.profiles.filter(p=>p.id!==c.profile_id);profiles.default_profile_id=profiles.profiles[0]?.id;profiles.revision++;result=structuredClone(profiles);}
        else if(c.op==='account_models') result={account,models:[{id:'model',display_name:'Model',is_default:true}]};
        else if(c.op==='start_account') result={session_id:c.session_id,workspace:c.workspace,incarnation:'10000000-0000-4000-8000-000000000003'};
        else throw Error(`Unexpected ${c.op}`);
        return {protocol:1,error:null,outcome_unknown:false,result};
    }};
    const settings=voyageSettings(root,{connections:new Map([['v',{id:'v',vessel_id:'vessel',name:'Computer',client,voyages:[]}]])},{current:()=>({vessel:'v'}),select:(...args)=>{selected=args;},apply:()=>{},draft:async(vessel,workspace)=>{origin={key:'draft-key',vessel,workspace,target:{type:'new_chat',workspace}};},captureDraft:()=>origin,unavailable:message=>{unavailableText=message;}});
    field('new-voyage').click();
    await until(()=>!field('setup-overview').hidden);
    await until(()=>profileOption() && !field('setup-manage-open').hidden,()=>`No profiles rendered. Status: ${field('edit-status').textContent}; operations: ${seen.map(command=>command.op).join(', ')}; unavailable: ${unavailableText}; origin: ${JSON.stringify(origin)}`);
    assert.equal(field('setup-dialog').querySelector('dialog')?.hasAttribute('open'),true);
    assert.ok(field('setup-location-open') && field('setup-profile-open'),'Setup starts with location and profile choices');
    field('setup-profile-open').click();
    assert.equal(field('setup-profiles').hidden,false);
    assert.equal(field('edit-model-section').hidden,true);
    field('setup-manage-open').click();
    assert.equal(field('setup-manage').hidden,false);
    field('profile-duplicate').click();
    await until(()=>!field('edit-save').disabled && !field('setup-editor').hidden);
    assert.equal(field('edit-model-section').hidden,false);
    assert.equal(field('edit-profile-name').value,'Default copy');
    assert.equal(field('edit-profile-name').closest('form'),null,'Enter in the profile editor cannot submit a message');
    field('edit-profile-name').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));
    assert.equal(seen.some(c=>c.op==='start_account'),false);
    field('setup-account-open').focus();
    field('setup-account-open').click();
    assert.equal(field('setup-picker').hidden,false,'account choice stays within Setup');
    assert.equal(field('edit-account').tagName,'UI-SELECT','account choices use a Flux listbox');
    assert.ok(field('edit-account').contains(document.activeElement),'account picker receives focus');
    field('setup-back').click();
    assert.equal(field('setup-editor').hidden,false);
    assert.equal(document.activeElement,field('setup-account-open'),'Back restores focus to the account trigger');
    field('setup-model-open').focus();
    field('setup-model-open').click();
    assert.equal(field('setup-picker').hidden,false,'model choice stays within Setup');
    assert.equal(field('edit-model').tagName,'UI-SELECT','model choices use a Flux listbox');
    assert.ok(field('edit-model').contains(document.activeElement),'model picker receives focus');
    field('setup-back').click();
    assert.equal(document.activeElement,field('setup-model-open'),'Back restores focus to the model trigger');
    field('edit-enroll').click();
    assert.equal(field('setup-enrollment').hidden,false,'account sign-in uses a Setup screen');
    assert.ok(field('setup-enrollment').contains(field('enrollment-panel')));
    field('enrollment-code').textContent='PRIVATE-FIXTURE-CODE';
    field('enrollment-private').hidden=false;
    field('setup-back').click();
    assert.equal(field('setup-editor').hidden,false);
    assert.equal(field('edit-profile-name').value,'Default copy','returning from sign-in keeps the profile edit');
    assert.equal(field('enrollment-code').textContent,'','Back clears the private sign-in code');
    assert.equal(field('enrollment-private').hidden,true);
    field('edit-save').click();await until(()=>profiles.profiles.length===2&&field('setup-manage').hidden===false);
    field('profile-edit').click();
    await until(()=>!field('setup-editor').hidden);
    field('setup-back').click();
    assert.equal(field('setup-manage').hidden,false,'Back from editor returns to management');
    field('setup-back').click();
    assert.equal(field('setup-profiles').hidden,false,'Back from management returns to profiles');
    assert.equal(field('edit-profiles-section').hidden,false,'profile choices reappear after leaving editor');
    field('setup-manage-open').click();
    field('profile-default').click();await until(()=>profiles.default_profile_id===profiles.profiles[1].id&&!field('profile-delete').disabled);
    assert.equal(seen.some(c=>c.op==='start_account'||c.op==='set_account_inference'),false);
    field('profile-delete').click();
    assert.equal(field('setup-delete').hidden,false,'deletion requires its own confirmation screen');
    assert.match(field('setup-delete-name').textContent,/Default/);
    assert.equal(profiles.profiles.length,2,'opening confirmation does not delete a profile');
    field('setup-delete-confirm').click();
    await until(()=>profiles.profiles.length===1&&!field('setup-manage').hidden);
    field('setup-back').click();
    assert.equal(field('setup-profiles').hidden,false,'Back from management returns to profile choice');
    field('setup-back').click();
    assert.equal(field('setup-overview').hidden,false,'Back returns to setup overview');
    field('setup-location-open').click();
    assert.equal(field('setup-location').hidden,false);
    assert.ok([...field('edit-workspace').options].some(o=>o.value==='__custom__'));
    field('edit-workspace').value='__custom__';
    field('edit-workspace').dispatchEvent(new Event('change'));
    assert.equal(field('edit-custom-workspace').hidden,false);
    field('edit-workspace-path').value='/new-folder';
    field('edit-workspace-path').dispatchEvent(new Event('input'));
    assert.equal(field('setup-done').hidden,true,'location is a screen within Setup');
    field('edit-workspace-path').dispatchEvent(new Event('change'));
    await until(()=>seen.some(c=>c.op==='accounts'&&c.workspace==='/new-folder') && profileOption());
    assert.notEqual(settings.configuration()?.workspace,'/new-folder','the new location needs profile review');
    field('setup-back').click();
    assert.match(field('setup-location-summary').textContent,/new-folder/);
    field('setup-profile-open').click();
    await until(()=>!field('edit-save').disabled);
    field('edit-profile').value=profileOption().getAttribute('value');
    field('edit-profile').dispatchEvent(new Event('change',{bubbles:true}));
    field('edit-save').click();
    await until(()=>settings.configuration()?.workspace === '/new-folder' && !field('setup-overview').hidden);
    field('setup-done').click();
    assert.equal(field('setup-dialog').querySelector('dialog')?.hasAttribute('open'),false);
    assert.equal(seen.some(c=>c.op==='start_account'),false);
    await settings.startDraft();
    await until(()=>selected);
    const start=seen.find(c=>c.op==='start_account');
    assert.equal(start.workspace,'/new-folder'); assert.deepEqual(start.account,account);
    const count=seen.length;
    field('edit-workspace-path').value='relative';
    field('edit-workspace-path').dispatchEvent(new Event('change'));
    assert.equal(seen.length,count);
    assert.match(field('edit-status').textContent,/absolute folder path/);
    scope='workspaces'; field('new-voyage').click();
    await until(()=>field('edit-workspace').value==='/known');
    field('setup-location-open').click();
    assert.equal(field('setup-location').hidden,false);
    assert.equal(field('edit-custom-workspace').hidden,true);
    assert.ok(![...field('edit-workspace').options].some(o=>o.value==='__custom__'));
    dom.window.close();
});
