import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {mkdtempSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {JSDOM} from 'jsdom';
import {voyageSettings} from '../resources/js/voyage-settings.js';

const settle = async () => { for (let i = 0; i < 30; i++) await Promise.resolve(); };
test('provider cards stay in the editor and usage loads automatically without stale account replies', async t => {
    const compiled = mkdtempSync(join(tmpdir(), 'helm-account-views-'));
    t.after(() => rmSync(compiled, {recursive:true, force:true}));
    const rendered = spawnSync('php', ['-r', `require 'vendor/autoload.php'; $app=require 'bootstrap/app.php'; $app->make(Illuminate\\Contracts\\Console\\Kernel::class)->bootstrap(); view()->share('errors',new Illuminate\\Support\\ViewErrorBag()); echo view('livewire.console',['vessels'=>collect(),'tenantId'=>'test'])->render();`], {cwd:new URL('..',import.meta.url), encoding:'utf8', env:{...process.env, VIEW_COMPILED_PATH:compiled}});
    assert.equal(rendered.status, 0, rendered.stderr);
    const dom = new JSDOM(rendered.stdout, {url:'https://helm.test/'});
    t.after(() => dom.window.close());
    for (const key of ['window','document','localStorage']) globalThis[key] = dom.window[key];
    t.after(() => { for (const key of ['window','document','localStorage']) delete globalThis[key]; });
    const root = document.querySelector('#helm-client'), $ = id => root.querySelector(`#${id}`);
    const binding = id => ({account_id:id, connection_id:'provider', identity_generation:1, connection_revision:1, transport:'openai_responses'});
    const target = {vessel:'local', session_id:'voyage', incarnation:'incarnation', inference:{account:binding('personal'), model:'model'}};
    const usage = [], requests = [];
    const reply = result => ({protocol:1, outcome_unknown:false, error:null, result});
    const client = {async exchange({command}) {
        requests.push(command);
        switch (command.op) {
            case 'capabilities': return reply({vessel_id:'vessel', scope:'owner'});
            case 'inspect': return reply({...target, workspace:'/work'});
            case 'accounts': return reply({accounts:['personal','work','unavailable'].map(id => ({id, connection_id:'provider', identity_generation:1, label:id, state:'ready', availability:id === 'unavailable' ? 'unavailable' : 'available'})), connections:[{id:'provider',label:'Provider',revision:1,transports:['openai_responses']}]});
            case 'profiles': return reply({revision:1, can_manage:true, default_profile_id:'profile', profiles:[{id:'profile', name:'Everyday', account:binding('personal'), model:'model'}]});
            case 'account_models': return reply({account:command.account, models:[{id:'model', reasoning_efforts:[], service_tiers:[]}]});
            case 'account_usage': return new Promise(resolve => usage.push({command, resolve:result => resolve(reply(result))}));
            default: throw Error(`Unexpected operation: ${command.op}`);
        }
    }};
    const connection = {id:'local', vessel_id:'vessel', name:'Local', client};
    voyageSettings(root, {connections:new Map([['local',connection]])}, {current:() => target});
    $('change-setup').click(); await settle();
    $('setup-profile-open').click(); $('setup-manage-open').click(); $('profile-edit').click(); await settle();
    assert.equal(usage.length, 2, 'opening the editor fetches usage for every available account');
    assert.equal(usage[0].command.refresh, true);
    assert.equal($('edit-account').localName, 'ui-radio-group');
    assert.equal($('edit-account').querySelectorAll('ui-radio').length, 3);
    assert.ok($('edit-account').querySelector('ui-radio[value="2"]').hasAttribute('disabled'));
    assert.ok($('setup-editor').contains($('edit-account')));
    $('setup-account-open').click();
    assert.equal($('setup-editor').hidden, false);
    assert.equal($('setup-picker').hidden, true);
    $('edit-account').value = '1';
    $('edit-account').dispatchEvent(new dom.window.Event('change', {bubbles:true})); await settle();
    assert.equal(usage.length, 2, 'selecting a card reuses its pending usage request');
    assert.equal(usage[1].command.account.account_id, 'work');
    assert.equal(usage[1].command.refresh, true);
    const personal = $('edit-account').querySelector('ui-radio[value="0"] [data-option-detail]');
    const work = $('edit-account').querySelector('ui-radio[value="1"] [data-option-detail]');
    usage[1].resolve({account:binding('work'),refresh_status:'fresh',snapshot:{fetched_at:1,windows:[{kind:'daily',used_percent:20}]}}); await settle();
    assert.match(work.textContent, /20% used/);
    assert.equal(work.querySelector('[data-usage-bar]').getAttribute('value'), '20');
    assert.equal(work.querySelector('[data-usage-bar]').getAttribute('aria-label'), 'daily usage');
    usage[0].resolve({account:binding('personal'),refresh_status:'fresh',snapshot:{fetched_at:1,windows:[{kind:'daily',used_percent:90}]}}); await settle();
    assert.match(personal.textContent, /90% used/);
    assert.match(work.textContent, /20% used/);
    assert.equal($('account-usage'), null, 'usage lives in the cards');
    assert.match($('edit-account').querySelector('ui-radio[value="2"] [data-option-detail]').textContent, /Unavailable/);
    $('profile-cancel-edit').click(); $('profile-edit').click(); await settle();
    usage[2].resolve({account:binding('work'),refresh_status:'fresh'}); await settle();
    assert.match($('edit-account').querySelector('ui-radio[value="0"] [data-option-detail]').textContent, /identity changed/);
    usage[3].resolve({account:binding('work'),refresh_status:'unsupported',snapshot:null}); await settle();
    assert.match($('edit-account').querySelector('ui-radio[value="1"] [data-option-detail]').textContent, /No usage information available/);
    $('profile-cancel-edit').click(); $('profile-edit').click(); await settle();
    const currentWork = $('edit-account').querySelector('ui-radio[value="1"] [data-option-detail]');
    $('setup-close').click();
    usage[4].resolve({account:binding('personal'),refresh_status:'fresh'});
    usage[5].resolve({account:binding('work'),refresh_status:'fresh',snapshot:{fetched_at:1,windows:[{kind:'daily',used_percent:70}]}}); await settle();
    assert.doesNotMatch(currentWork.textContent, /70%/);
});
