import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {spawnSync} from 'node:child_process';
import {sidebarActions} from '../resources/js/sidebar-actions.js';
import {IntentJournal} from '../resources/js/vessel-client.js';
import {validCommand} from '../gateway/protocol.js';
const dom=new JSDOM('',{url:'https://fixture.invalid'});
for(const key of ['window','document','localStorage','Event','MouseEvent','Option']) globalThis[key]=dom.window[key];
const rendered=spawnSync('php',['-r',`require 'vendor/autoload.php'; $app=require 'bootstrap/app.php'; $app->make(Illuminate\\Contracts\\Console\\Kernel::class)->bootstrap(); view()->share('errors',new Illuminate\\Support\\ViewErrorBag()); echo view('livewire.console',['vessels'=>collect(),'tenantId'=>'test'])->render();`],{cwd:new URL('..',import.meta.url),encoding:'utf8'});
assert.equal(rendered.status,0,rendered.stderr);
const id='11111111-1111-4111-8111-111111111111', inc='22222222-2222-4222-8222-222222222222', other='33333333-3333-4333-8333-333333333333';
const pause=()=>new Promise(r=>setTimeout(r,3));
async function until(fn){for(let i=0;i<150;i++){if(fn())return;await pause();}assert.fail('timed out');}
function fixture(){
 localStorage.clear();const host=document.createElement('div');host.innerHTML=rendered.stdout;document.body.append(host);
 const $=x=>host.querySelector('#sidebar-'+x), calls=[], receipts=new Map(), children=new Map();
 const state={revision:7,stopped:false,archived:false,lost:false,run:false,scope:'owner',inspectGate:null};
 const connection={name:'Vessel A',journal:new IntentJournal(localStorage,'menu')};
 connection.client={async exchange({command:c}){calls.push(c);assert.equal(validCommand({type:"command",request_id:inc,request:{protocol:1,command:c}}),true,JSON.stringify(c));if(c.session_id)assert.ok(c.session_id===id||children.has(c.session_id));let result;
 if(c.op==='capabilities')result={scope:state.scope,rights:['history','lifecycle','create','cancel','execute']};
 else if(c.op==='inspect'){if(state.inspectGate)await state.inspectGate;result=children.get(c.session_id)||{session_id:id,incarnation:state.stopped?inc:state.restarted?other:inc,state:state.stopped?'stopped':'live',archive:state.archived?{}:null};}
 else if(c.op==='snapshot')result={session_id:id,incarnation:state.restarted?other:inc,result:{session_id:id,revision:state.revision,name:'Target',access:'approval',messages:[],lifecycle:{archived:state.archived},run:state.run?{run_id:other,state:'running'}:null}};
 else if(c.op==='history')result={session_id:id,incarnation:inc,result:{revision:7,message_offset:0,next_offset:2,has_more:false,messages:[{role:'user'},{role:'assistant'}]}};
 else if(c.op==='receipt')result={session_id:id,incarnation:inc,result:receipts.get(c.command_id)||{command_id:c.command_id,status:'unknown'}};
 else if(c.op==='restart'){state.stopped=false;state.restarted=true;result={session_id:id,incarnation:other};if(state.lost){state.lost=false;throw Error('lost restart reply');}}
 else {const receipt={command_id:c.command_id,status:c.op==='branch'?'snapshot_committed':'applied',...(c.branch_id?{branch_id:c.branch_id}:{})};receipts.set(c.command_id,receipt);result={session_id:id,incarnation:state.restarted?other:inc,result:receipt}; if(c.op==='branch'){children.set(c.branch_id,{session_id:c.branch_id,incarnation:other,state:'live'});result=children.get(c.branch_id);} if(c.op==='archive')state.archived=c.archived; if(state.lost){state.lost=false;throw Error('lost reply');}}
 return {protocol:1,outcome_unknown:false,error:null,result};}};
 const controller=sidebarActions(host,{modal:()=>({show(){},close(){}})});
 const item={session_id:id,name:'Target'};
 const node=host.querySelector('#flux-voyage').content.firstElementChild.cloneNode(true);host.querySelector('#voyages').append(node);controller.bind(node,connection,item);
 return {state,connection,calls,receipts,children,$,node,controller,async open(action){await controller.open(connection,item,action);},async send(){const count=calls.length;$('action-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await pause();await pause();},dispose(){controller.invalidate();host.remove();}};
}
test('rendered Flux context has sibling select/ellipsis, keyboard access and visible reasons',async()=>{const f=fixture();try{assert.equal(f.node.tagName,'UI-CONTEXT');assert.equal(f.node.querySelectorAll('button button').length,0);assert.equal(f.node.querySelector('[data-voyage-actions]').hasAttribute('data-flux-sidebar-item'),false);f.node.querySelector('[data-voyage-row]').dispatchEvent(new window.KeyboardEvent('keydown',{key:'F10',shiftKey:true,bubbles:true,cancelable:true}));await until(()=>!f.node.querySelector('[data-voyage-action="rename"]').disabled);assert.match(f.node.querySelector('[data-voyage-action="cancel"]').textContent,/no active run/);}finally{f.dispose();}});
test('each targeted mutation uses clicked unselected identity and fresh revision; destructive confirmation',async()=>{for(const action of ['rename','access','archive','branch','cancel','clear','compact','delete']){const f=fixture();try{f.state.run=action==='cancel';await f.open(action);if(action==='rename')f.$('name').value='Changed';if(['clear','compact','delete'].includes(action))f.$('confirm').value=action.toUpperCase();await f.send();await until(()=>f.calls.some(c=>c.op===(action==='access'?'set_access':action)));const c=f.calls.find(c=>c.op===(action==='access'?'set_access':action));assert.equal(c.session_id,id);assert.equal(c.expected_revision,7);assert.equal(c.incarnation,inc);if(action==='cancel')assert.equal(c.run_id,other);if(action==='compact')assert.equal(c.preserve_canonical,true);if(action==='branch')assert.equal(c.through_message,null);assert.equal(f.connection.journal.entries().length,0);}finally{f.dispose();}}});
test('revision and selection fences prevent stale effects, confirmation refuses empty word',async()=>{for(const mode of ['revision','selection','confirm']){const f=fixture();try{await f.open(mode==='confirm'?'delete':'rename');f.$('name').value='Change';if(mode==='revision')f.state.revision++;if(mode==='selection')f.controller.invalidate();await f.send();assert.equal(f.calls.some(c=>['rename','delete'].includes(c.op)),false);}finally{f.dispose();}}});
test('uncertain branch reconciles source receipt AND child, without replay and without storing text',async()=>{const f=fixture();try{await f.open('branch');f.$('name').value='private name';f.state.lost=true;await f.send();await until(()=>f.connection.journal.entries().length===1);const entry=f.connection.journal.entries()[0];assert.ok(entry.branch_id);assert.equal(JSON.stringify(entry).includes('private name'),false);await f.controller.reconcile();assert.equal(f.connection.journal.entries().length,0);assert.equal(f.calls.filter(c=>c.op==='branch').length,1);}finally{f.dispose();}});
test('lost rename receipt reconciles, does not replay; stopped archived restore restarts then snapshots',async()=>{const f=fixture();try{await f.open('rename');f.$('name').value='Name';f.state.lost=true;await f.send();await f.controller.reconcile();assert.equal(f.calls.filter(c=>c.op==='rename').length,1);assert.equal(f.connection.journal.entries().length,0);f.state.stopped=true;f.state.archived=true;await f.open('archive');assert.equal(f.$('submit').disabled,false);await f.send();await until(()=>f.calls.some(c=>c.op==='archive'));const restart=f.calls.find(c=>c.op==='restart'),archive=f.calls.find(c=>c.op==='archive');assert.equal(archive.archived,false);assert.equal(archive.incarnation,other);assert.equal(archive.command_id,restart.command_id);}finally{f.dispose();}});
test('scoped owner-only actions refuse; details remains available for stopped voyage',async()=>{const f=fixture();try{f.state.scope='session';await f.open('access');assert.equal(f.$('submit').disabled,true);f.state.stopped=true;await f.open('details');assert.match(f.$('action-details').textContent,/stopped/);}finally{f.dispose();}});
test('missing child or mismatched branch receipt retains uncertainty and never replays',async()=>{for(const mismatch of [false,true]){const f=fixture();try{await f.open('branch');f.state.lost=true;await f.send();const entry=f.connection.journal.entries()[0];if(mismatch)f.receipts.get(entry.command_id).branch_id=other;else f.children.clear();await f.controller.reconcile();assert.equal(f.connection.journal.entries().length,1);assert.equal(f.calls.filter(c=>c.op==='branch').length,1);}finally{f.dispose();}}});
test('live archived Restore skips restart; historical branch boundary is explicit',async()=>{const f=fixture();try{f.state.archived=true;await f.open('archive');await f.send();assert.equal(f.calls.filter(c=>c.op==='restart').length,0);assert.equal(f.calls.find(c=>c.op==='archive').archived,false);await f.open('branch');f.$('branch').value='0';await f.send();assert.equal(f.calls.find(c=>c.op==='branch').through_message,0);}finally{f.dispose();}});
test('gateway rejects destructive operation missing confirmation/preservation and extra authority',()=>{const valid=c=>validCommand({type:'command',request_id:inc,request:{protocol:1,command:c}}),base={session_id:id,incarnation:inc,command_id:other,expected_revision:7,expires_at_ms:123};assert.equal(valid({op:'clear',...base}),false);assert.equal(valid({op:'compact',...base,retain:128,preserve_canonical:false}),false);assert.equal(valid({op:'restart',session_id:id,incarnation:inc,command_id:other,force:true}),false);});
test('uncertain restart is observed without replay, then explicit Restore completes unarchive',async()=>{const f=fixture();try{f.state.stopped=true;f.state.archived=true;await f.open('archive');f.state.lost=true;await f.send();assert.equal(f.connection.journal.entries()[0].op,'restart');await f.controller.reconcile();assert.match(f.$('action-status').textContent,/observed/);assert.equal(f.connection.journal.entries().length,0);await f.open('archive');await f.send();assert.equal(f.calls.filter(c=>c.op==='restart').length,1);assert.equal(f.calls.find(c=>c.op==='archive').archived,false);}finally{f.dispose();}});
test('selection changed during fresh confirmation read fences the mutation',async()=>{const f=fixture();try{await f.open('rename');f.$('name').value='Change';let release;f.state.inspectGate=new Promise(resolve=>release=resolve);f.$('action-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await pause();f.controller.invalidate();release();await pause();assert.equal(f.calls.some(c=>c.op==='rename'),false);}finally{f.dispose();}});
