import React,{useEffect,useRef,useState} from 'react';
import {Enrollment} from './Enrollment';
import {accountChoices,Creation,vesselRead} from './settings';
import type {Tab,Workspace} from './workspace';
export function Settings({fleet,workspace,tab,tenant,onClose,onCreated}:{fleet:any;workspace:Workspace;tab?:Tab;tenant:string;onClose:()=>void;onCreated:(vessel:string,process:any)=>void}){
    const dialog=useRef<HTMLDialogElement>(null);
    const [vessel,setVessel]=useState(tab?.vessel||[...fleet.connections.keys()][0]||'');
    const [caps,setCaps]=useState<any>(null),[path,setPath]=useState(''),[accounts,setAccounts]=useState<any[]>([]),[account,setAccount]=useState(''),[models,setModels]=useState<any[]>([]),[model,setModel]=useState(''),[reasoning,setReasoning]=useState(''),[service,setService]=useState('');
    const [usage,setUsage]=useState('');
    const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[recovery,setRecovery]=useState(0);
    const connection=fleet.connections.get(vessel),selected=accounts[Number(account)],selectedModel=models.find(item=>item.id===model);
    const usageGeneration=useRef(0);
    useEffect(()=>{usageGeneration.current++;setUsage('');return()=>{usageGeneration.current++;};},[vessel,path,account]);
    const creation=useRef<Creation|null>(null),origin=useRef({incarnation:tab?.incarnation,revision:tab?.snapshot?.revision});
    useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
    useEffect(()=>{let alive=true;setCaps(null);setPath('');setAccounts([]);setNotice('Loading Vessel…');
        vesselRead(connection,'capabilities').then(async value=>{if(value.vessel_id!==connection.vessel_id)throw new Error('Vessel identity changed.');if(value.scope!=='owner'&&(!value.rights?.includes('account_use')||(!tab&&!value.rights?.includes('create'))))throw new Error('This connection does not permit account use or creation.');let location=tab?.snapshot?.workspace||'';if(tab){const process=await vesselRead(connection,'inspect',{session_id:tab.session});if(process.incarnation!==tab.incarnation)throw new Error('Voyage changed. Reopen settings.');location=process.workspace;}if(alive){setCaps(value);setPath(location||value.workspaces?.[0]?.path||'');setNotice('');}}).catch(error=>alive&&setNotice(error.message));return()=>{alive=false;};
    },[vessel,connection?.client]);
    useEffect(()=>{let alive=true;setAccounts([]);setAccount('');setModels([]);if(!path.startsWith('/'))return;
        setNotice('Loading provider accounts…');vesselRead(connection,'accounts',{workspace:path,transport:null}).then(value=>{if(alive){const choices=accountChoices(value);setAccounts(choices);setAccount(String(Math.max(0,choices.findIndex((item:any)=>item.ready&&['account_id','connection_id','identity_generation','connection_revision','transport'].every(key=>item.binding[key]===(tab?.snapshot?.inference?.account||value.default_account)?.[key])))));setNotice(choices.length?'':'No provider accounts available.');}}).catch(error=>alive&&setNotice(error.message));return()=>{alive=false;};
    },[path,vessel,connection?.client,recovery]);
    useEffect(()=>{let alive=true;setModels([]);setModel('');if(!selected?.ready)return;setNotice('Loading models…');vesselRead(connection,'account_models',{workspace:path,account:selected.binding}).then(value=>{if(!alive)return;if(JSON.stringify(value.account)!==JSON.stringify(selected.binding)){
            const keys=['account_id','connection_id','identity_generation','connection_revision','transport'];if(keys.some(key=>value.account?.[key]!==selected.binding[key]))throw new Error('Account identity changed.');
        }const same=['account_id','connection_id','identity_generation','connection_revision','transport'].every(key=>selected.binding[key]===tab?.snapshot?.inference?.account?.[key]);setModels(value.models||[]);setModel((same?value.models?.find((item:any)=>item.id===tab?.snapshot?.inference?.model)?.id:null)||value.models?.find((item:any)=>item.is_default)?.id||value.models?.[0]?.id||'');setReasoning(same?tab?.snapshot?.inference?.reasoning_effort||'':'');setService(same?tab?.snapshot?.inference?.service_tier||'':'');setNotice('');}).catch(error=>alive&&setNotice(error.message));return()=>{alive=false;};},[account,accounts]);
    const pending=()=>{try{creation.current??=new Creation(localStorage,tenant);return {records:creation.current.pending(),error:false};}catch{return {records:[],error:true};}};
    const recoveryState=pending(),records=recoveryState.records;
    async function save(){if(busy||!caps||!selected?.ready||!selectedModel)return;setBusy(true);try{
        const settings={account:selected.binding,model,reasoning_effort:reasoning||null,service_tier:service||null};
        if(tab){if(['running','starting','cancelling'].includes(tab.snapshot?.run?.state))throw new Error('Wait for the current run to finish before changing inference settings.');if(tab.incarnation!==origin.current.incarnation||tab.snapshot?.revision!==origin.current.revision)throw new Error('Voyage changed since review. Reopen settings.');if(!await workspace.act(tab.key,'set_account_inference',settings))throw new Error('Settings were not confirmed. Check the voyage receipt before retrying.');onClose();}
        else {creation.current??=new Creation(localStorage,tenant);const process=await creation.current.start(connection,path,settings);onCreated(vessel,process);onClose();}
    }catch(error){setNotice(error instanceof Error?error.message:'Settings unavailable.');}finally{setBusy(false);setRecovery(recovery+1);}}
    return <dialog ref={dialog} className="settings-dialog" onCancel={event=>{if(busy)event.preventDefault();else onClose();}}><form onSubmit={event=>{event.preventDefault();void save();}}><header><h2>{tab?'Voyage settings':'New voyage'}</h2><button type="button" disabled={busy} aria-label="Close settings" onClick={onClose}>×</button></header><p>Choose where your voyage runs and which provider account it uses. Credentials stay on the Vessel.</p>
        <label>Vessel<select disabled={!!tab||busy} value={vessel} onChange={event=>setVessel(event.target.value)}>{[...fleet.connections.values()].map((item:any)=><option key={item.id} value={item.id}>{item.name}{!item.client?' · offline':''}</option>)}</select></label>
        <label>Workspace{caps?.scope==='owner'&&!tab?<input value={path} onChange={event=>setPath(event.target.value)} placeholder="Existing absolute folder on this Vessel" disabled={busy}/>:<select disabled={!!tab||busy} value={path} onChange={event=>setPath(event.target.value)}>{tab?<option value={path}>{path}</option>:(caps?.workspaces||[]).map((item:any)=><option key={item.path} value={item.path}>{item.name} · {item.path}</option>)}</select>}</label>
        <label>Provider account<select disabled={busy} value={account} onChange={event=>setAccount(event.target.value)}>{accounts.map((item,index)=><option key={index} value={index} disabled={!item.ready}>{item.label}{!item.ready?' · unavailable':''}</option>)}</select></label>
        {connection&&path&&<Enrollment connection={connection} workspace={path} tenant={tenant} onRefreshed={()=>setRecovery(value=>value+1)}/>}
        <details><summary>Account usage</summary><pre>{usage||'No usage observation loaded. This is not zero usage.'}</pre><button type="button" disabled={busy||!selected?.ready} onClick={async()=>{const epoch=++usageGeneration.current;setUsage('Loading…');try{const value=await vesselRead(connection,'account_usage',{workspace:path,account:selected.binding,refresh:true});if(epoch===usageGeneration.current){if(['account_id','connection_id','identity_generation','connection_revision','transport'].some(key=>value.account?.[key]!==selected.binding[key]))throw new Error('Account usage identity changed.');setUsage(JSON.stringify(value,null,2));}}catch(error){if(epoch===usageGeneration.current)setUsage(error instanceof Error?error.message:'Usage unavailable.');}}}>Refresh usage</button></details>
        <label>Model<select disabled={busy} value={model} onChange={event=>{setModel(event.target.value);setReasoning('');setService('');}}>{models.map(item=><option key={item.id} value={item.id}>{item.display_name||item.id}</option>)}</select></label>
        <label>Reasoning<select value={reasoning} disabled={busy} onChange={event=>setReasoning(event.target.value)}><option value="">Provider default</option>{[...new Set([...(selectedModel?.reasoning_efforts||[]),...(reasoning?[reasoning]:[])])].map((value:any)=><option key={value}>{value}</option>)}</select></label>
        <label>Service tier<select value={service} disabled={busy} onChange={event=>setService(event.target.value)}><option value="">Provider default</option>{[...new Set([...(selectedModel?.service_tiers||[]),...(service?[service]:[])])].map((value:any)=><option key={value}>{value}</option>)}</select></label>
        <p role="status">{recoveryState.error?'Recovery storage is unavailable. Do not clear it or repeat uncertain creation.':notice}</p>{records.map(record=><button type="button" key={record.key} disabled={busy} onClick={async()=>{setBusy(true);try{const c=fleet.connections.get(record.vessel);const process=await creation.current!.reconcile(c,record);if(process){onCreated(c.id,process);onClose();}else setNotice('Creation was not admitted. You can review and try again.');}catch(error){setNotice(error instanceof Error?error.message:'Receipt unavailable.');}finally{setBusy(false);setRecovery(recovery+1);}}}>Check creation · {record.vessel}</button>)}<footer><button type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-action" disabled={busy||recoveryState.error||!caps||!selected?.ready||!selectedModel||(!tab&&!path.startsWith('/'))}>{busy?'Working…':tab?'Apply':'Create voyage'}</button></footer>
    </form></dialog>;
}
